{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Email Analysis *Extract, Load, and Transform* Notebook"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Imports"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Standard Library Imports\n",
    "import logging\n",
    "from typing import List, Dict, Any\n",
    "from datetime import datetime\n",
    "\n",
    "# Third-Party Imports\n",
    "import pypff # type: ignore\n",
    "from sqlalchemy.exc import SQLAlchemyError\n",
    "\n",
    "# Local Imports\n",
    "from src.utils.config import Config\n",
    "from src.extract.pst_message_extractor import PstMessageExtractor\n",
    "from src.transform.message_parser import MessageParser, ParsedMessage\n",
    "from src.transform.message_enricher import MessageEnricher, EnrichedMessage\n",
    "from src.load.data_loader import DataLoader\n",
    "\n",
    "logging.basicConfig(level=logging.INFO)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Configuration"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "config: Config = Config.from_json(\"config.json\")\n",
    "extractor: PstMessageExtractor = PstMessageExtractor(config.input_pst_path, config.chunk_size)\n",
    "message_parser: MessageParser = MessageParser()\n",
    "message_enricher: MessageEnricher = MessageEnricher()\n",
    "loader: DataLoader = DataLoader(host=config.db_host, user=config.db_user, password=config.db_password, database=config.db_name)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### ETL Pipeline with Error Handling"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "INFO:root:Database tables created successfully\n",
      "INFO:root:Skipping empty folder: Deleted Items\n",
      "INFO:root:Extracting messages from folder: Inbox\n",
      "INFO:langid.langid:initializing identifier\n",
      "ERROR:root:Error while loading data into database: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n",
      "(pymysql.err.IntegrityError) (1062, \"Duplicate entry 'CANc0Yq66py_2t28pJ0H6E47s_BRZv1qR6O9=KFp2wqUC+WDzAA@mail.gmail.c' for key 'messages.global_message_id'\")\n",
      "[SQL: INSERT INTO messages (global_message_id, folder_id, from_address_id, provider_email_id, creation_time, submit_time, delivery_time, sender_name, in_reply_to, subject, body, first_in_thread, previous_message_id, domain, language, spam_score, from_internal_domain, subject_prefix) VALUES (%(global_message_id)s, %(folder_id)s, %(from_address_id)s, %(provider_email_id)s, %(creation_time)s, %(submit_time)s, %(delivery_time)s, %(sender_name)s, %(in_reply_to)s, %(subject)s, %(body)s, %(first_in_thread)s, %(previous_message_id)s, %(domain)s, %(language)s, %(spam_score)s, %(from_internal_domain)s, %(subject_prefix)s)]\n",
      "[parameters: {'global_message_id': 'CANc0Yq66py_2t28pJ0H6E47s_BRZv1qR6O9=KFp2wqUC+WDzAA@mail.gmail.com', 'folder_id': 12, 'from_address_id': 12, 'provider_email_id': 2097188, 'creation_time': datetime.datetime(2024, 7, 2, 8, 27, 33, 792913, tzinfo=datetime.timezone.utc), 'submit_time': datetime.datetime(2024, 6, 30, 5, 6, 15, tzinfo=datetime.timezone.utc), 'delivery_time': datetime.datetime(2024, 6, 30, 5, 6, 26, tzinfo=datetime.timezone.utc), 'sender_name': 'Mohammed Alsahal', 'in_reply_to': '<CANc0Yq7Oy8un7hjwvQsEJyum4-p905KNjfPscOpabNgtC1JZmQ@mail.gmail.com>', 'subject': 'QSTP summer Workshops Program', 'body': None, 'first_in_thread': 0, 'previous_message_id': '<CANc0Yq7Oy8un7hjwvQsEJyum4-p905KNjfPscOpabNgtC1JZmQ@mail.gmail.com>', 'domain': 'gmail.com', 'language': None, 'spam_score': None, 'from_internal_domain': 0, 'subject_prefix': None}]\n",
      "(Background on this error at: https://sqlalche.me/e/20/gkpj)\n",
      "INFO:root:Loaded 250 messages in batch 1\n",
      "ERROR:root:Error while loading data into database: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n",
      "(pymysql.err.IntegrityError) (1062, \"Duplicate entry 'CABrjX5F=8YTcie3qDY3Bw1SO8DPiGSz9pHq9p_SuscT1zt11fQ@mail.gmail.c' for key 'messages.global_message_id'\")\n",
      "[SQL: INSERT INTO messages (global_message_id, folder_id, from_address_id, provider_email_id, creation_time, submit_time, delivery_time, sender_name, in_reply_to, subject, body, first_in_thread, previous_message_id, domain, language, spam_score, from_internal_domain, subject_prefix) VALUES (%(global_message_id)s, %(folder_id)s, %(from_address_id)s, %(provider_email_id)s, %(creation_time)s, %(submit_time)s, %(delivery_time)s, %(sender_name)s, %(in_reply_to)s, %(subject)s, %(body)s, %(first_in_thread)s, %(previous_message_id)s, %(domain)s, %(language)s, %(spam_score)s, %(from_internal_domain)s, %(subject_prefix)s)]\n",
      "[parameters: {'global_message_id': 'CABrjX5F=8YTcie3qDY3Bw1SO8DPiGSz9pHq9p_SuscT1zt11fQ@mail.gmail.com', 'folder_id': 12, 'from_address_id': 122, 'provider_email_id': 2105188, 'creation_time': datetime.datetime(2024, 7, 2, 8, 27, 43, 350252, tzinfo=datetime.timezone.utc), 'submit_time': datetime.datetime(2017, 7, 31, 19, 44, 8, tzinfo=datetime.timezone.utc), 'delivery_time': datetime.datetime(2017, 7, 31, 19, 44, 11, tzinfo=datetime.timezone.utc), 'sender_name': 'Nate Spell', 'in_reply_to': None, 'subject': 'Them Magazines: 3 Ways To Get Yourself Inside Our Next Issue', 'body': None, 'first_in_thread': 1, 'previous_message_id': None, 'domain': 'themmagazines.com', 'language': None, 'spam_score': None, 'from_internal_domain': 0, 'subject_prefix': None}]\n",
      "(Background on this error at: https://sqlalche.me/e/20/gkpj)\n",
      "INFO:root:Loaded 250 messages in batch 2\n",
      "ERROR:root:Error while loading data into database: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n",
      "(pymysql.err.IntegrityError) (1062, \"Duplicate entry '0.1.51.85B.1D359846CEA145A.0@omp.emails.wix.com' for key 'messages.global_message_id'\")\n",
      "[SQL: INSERT INTO messages (global_message_id, folder_id, from_address_id, provider_email_id, creation_time, submit_time, delivery_time, sender_name, in_reply_to, subject, body, first_in_thread, previous_message_id, domain, language, spam_score, from_internal_domain, subject_prefix) VALUES (%(global_message_id)s, %(folder_id)s, %(from_address_id)s, %(provider_email_id)s, %(creation_time)s, %(submit_time)s, %(delivery_time)s, %(sender_name)s, %(in_reply_to)s, %(subject)s, %(body)s, %(first_in_thread)s, %(previous_message_id)s, %(domain)s, %(language)s, %(spam_score)s, %(from_internal_domain)s, %(subject_prefix)s)]\n",
      "[parameters: {'global_message_id': '0.1.51.85B.1D359846CEA145A.0@omp.emails.wix.com', 'folder_id': 12, 'from_address_id': 73, 'provider_email_id': 2113188, 'creation_time': datetime.datetime(2024, 7, 2, 8, 27, 52, 514515, tzinfo=datetime.timezone.utc), 'submit_time': datetime.datetime(2017, 11, 9, 17, 59, 2, tzinfo=datetime.timezone.utc), 'delivery_time': datetime.datetime(2017, 11, 9, 18, 46, 47, tzinfo=datetime.timezone.utc), 'sender_name': 'Wix.com', 'in_reply_to': None, 'subject': 'Get Your Website Holiday Ready', 'body': None, 'first_in_thread': 1, 'previous_message_id': None, 'domain': 'emails.wix.com', 'language': None, 'spam_score': None, 'from_internal_domain': 0, 'subject_prefix': None}]\n",
      "(Background on this error at: https://sqlalche.me/e/20/gkpj)\n",
      "INFO:root:Loaded 250 messages in batch 3\n",
      "ERROR:root:Error while loading data into database: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n",
      "(pymysql.err.IntegrityError) (1062, \"Duplicate entry 'ec2578a0.AEMAScRrcLwAAAAI0YIAAAAV8aQAAAAAACMAAAAAAAR5bABaaEnh@ma' for key 'messages.global_message_id'\")\n",
      "[SQL: INSERT INTO messages (global_message_id, folder_id, from_address_id, provider_email_id, creation_time, submit_time, delivery_time, sender_name, in_reply_to, subject, body, first_in_thread, previous_message_id, domain, language, spam_score, from_internal_domain, subject_prefix) VALUES (%(global_message_id)s, %(folder_id)s, %(from_address_id)s, %(provider_email_id)s, %(creation_time)s, %(submit_time)s, %(delivery_time)s, %(sender_name)s, %(in_reply_to)s, %(subject)s, %(body)s, %(first_in_thread)s, %(previous_message_id)s, %(domain)s, %(language)s, %(spam_score)s, %(from_internal_domain)s, %(subject_prefix)s)]\n",
      "[parameters: {'global_message_id': 'ec2578a0.AEMAScRrcLwAAAAI0YIAAAAV8aQAAAAAACMAAAAAAAR5bABaaEnh@mailjet.com', 'folder_id': 12, 'from_address_id': 80, 'provider_email_id': 2121188, 'creation_time': datetime.datetime(2024, 7, 2, 8, 27, 59, 55240, tzinfo=datetime.timezone.utc), 'submit_time': datetime.datetime(2018, 1, 24, 8, 54, 57, tzinfo=datetime.timezone.utc), 'delivery_time': datetime.datetime(2018, 1, 24, 8, 54, 58, tzinfo=datetime.timezone.utc), 'sender_name': 'Sketchfab', 'in_reply_to': None, 'subject': 'Your weekly digest', 'body': None, 'first_in_thread': 1, 'previous_message_id': None, 'domain': 'sketchfab.com', 'language': None, 'spam_score': None, 'from_internal_domain': 0, 'subject_prefix': None}]\n",
      "(Background on this error at: https://sqlalche.me/e/20/gkpj)\n",
      "INFO:root:Loaded 250 messages in batch 4\n",
      "ERROR:root:Error while loading data into database: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n",
      "(pymysql.err.IntegrityError) (1062, \"Duplicate entry '0101016279f1bbed-45a71411-99fe-493c-b143-2a3c82f9a319-000000@us-' for key 'messages.global_message_id'\")\n",
      "[SQL: INSERT INTO messages (global_message_id, folder_id, from_address_id, provider_email_id, creation_time, submit_time, delivery_time, sender_name, in_reply_to, subject, body, first_in_thread, previous_message_id, domain, language, spam_score, from_internal_domain, subject_prefix) VALUES (%(global_message_id)s, %(folder_id)s, %(from_address_id)s, %(provider_email_id)s, %(creation_time)s, %(submit_time)s, %(delivery_time)s, %(sender_name)s, %(in_reply_to)s, %(subject)s, %(body)s, %(first_in_thread)s, %(previous_message_id)s, %(domain)s, %(language)s, %(spam_score)s, %(from_internal_domain)s, %(subject_prefix)s)]\n",
      "[parameters: {'global_message_id': '0101016279f1bbed-45a71411-99fe-493c-b143-2a3c82f9a319-000000@us-west-2.amazonses.com', 'folder_id': 12, 'from_address_id': 120, 'provider_email_id': 2129188, 'creation_time': datetime.datetime(2024, 7, 2, 8, 28, 6, 131566, tzinfo=datetime.timezone.utc), 'submit_time': datetime.datetime(2018, 3, 31, 2, 45, 8, tzinfo=datetime.timezone.utc), 'delivery_time': datetime.datetime(2018, 3, 31, 2, 45, 9, tzinfo=datetime.timezone.utc), 'sender_name': 'Streamlabs', 'in_reply_to': None, 'subject': 'How’s it going?', 'body': None, 'first_in_thread': 1, 'previous_message_id': None, 'domain': 'streamlabs.com', 'language': None, 'spam_score': None, 'from_internal_domain': 0, 'subject_prefix': None}]\n",
      "(Background on this error at: https://sqlalche.me/e/20/gkpj)\n",
      "INFO:root:Loaded 250 messages in batch 5\n",
      "ERROR:root:Error while loading data into database: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n",
      "(pymysql.err.IntegrityError) (1062, \"Duplicate entry '0100016376d21ef2-05cf342a-2a62-4e98-834b-52b06587bd25-000000@ema' for key 'messages.global_message_id'\")\n",
      "[SQL: INSERT INTO messages (global_message_id, folder_id, from_address_id, provider_email_id, creation_time, submit_time, delivery_time, sender_name, in_reply_to, subject, body, first_in_thread, previous_message_id, domain, language, spam_score, from_internal_domain, subject_prefix) VALUES (%(global_message_id)s, %(folder_id)s, %(from_address_id)s, %(provider_email_id)s, %(creation_time)s, %(submit_time)s, %(delivery_time)s, %(sender_name)s, %(in_reply_to)s, %(subject)s, %(body)s, %(first_in_thread)s, %(previous_message_id)s, %(domain)s, %(language)s, %(spam_score)s, %(from_internal_domain)s, %(subject_prefix)s)]\n",
      "[parameters: {'global_message_id': '0100016376d21ef2-05cf342a-2a62-4e98-834b-52b06587bd25-000000@email.amazonses.com', 'folder_id': 12, 'from_address_id': 104, 'provider_email_id': 2137220, 'creation_time': datetime.datetime(2024, 7, 2, 8, 28, 22, 511247, tzinfo=datetime.timezone.utc), 'submit_time': datetime.datetime(2018, 5, 19, 5, 14, 32, tzinfo=datetime.timezone.utc), 'delivery_time': datetime.datetime(2018, 5, 19, 5, 14, 32, tzinfo=datetime.timezone.utc), 'sender_name': 'IslamicFinder Weekly', 'in_reply_to': None, 'subject': 'Ramadan fun with IslamicFinder', 'body': None, 'first_in_thread': 1, 'previous_message_id': None, 'domain': 'islamicfinder.org', 'language': None, 'spam_score': None, 'from_internal_domain': 0, 'subject_prefix': None}]\n",
      "(Background on this error at: https://sqlalche.me/e/20/gkpj)\n",
      "INFO:root:Loaded 250 messages in batch 6\n",
      "ERROR:root:Error while loading data into database: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n",
      "(pymysql.err.IntegrityError) (1062, \"Duplicate entry '767065ce-27d5-4f7c-8c84-b84c21661d1c@technolutions.net' for key 'messages.global_message_id'\")\n",
      "[SQL: INSERT INTO messages (global_message_id, folder_id, from_address_id, provider_email_id, creation_time, submit_time, delivery_time, sender_name, in_reply_to, subject, body, first_in_thread, previous_message_id, domain, language, spam_score, from_internal_domain, subject_prefix) VALUES (%(global_message_id)s, %(folder_id)s, %(from_address_id)s, %(provider_email_id)s, %(creation_time)s, %(submit_time)s, %(delivery_time)s, %(sender_name)s, %(in_reply_to)s, %(subject)s, %(body)s, %(first_in_thread)s, %(previous_message_id)s, %(domain)s, %(language)s, %(spam_score)s, %(from_internal_domain)s, %(subject_prefix)s)]\n",
      "[parameters: {'global_message_id': '767065ce-27d5-4f7c-8c84-b84c21661d1c@technolutions.net', 'folder_id': 12, 'from_address_id': 760, 'provider_email_id': 2145220, 'creation_time': datetime.datetime(2024, 7, 2, 8, 28, 28, 613680, tzinfo=datetime.timezone.utc), 'submit_time': datetime.datetime(2018, 7, 27, 2, 36, 48, tzinfo=datetime.timezone.utc), 'delivery_time': datetime.datetime(2018, 7, 27, 2, 36, 50, tzinfo=datetime.timezone.utc), 'sender_name': 'Madalyn Ridge', 'in_reply_to': None, 'subject': 'I was in your place exactly a year ago', 'body': None, 'first_in_thread': 1, 'previous_message_id': None, 'domain': 'xavier.edu', 'language': None, 'spam_score': None, 'from_internal_domain': 0, 'subject_prefix': None}]\n",
      "(Background on this error at: https://sqlalche.me/e/20/gkpj)\n",
      "INFO:root:Loaded 250 messages in batch 7\n",
      "ERROR:root:Error while loading data into database: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n",
      "(pymysql.err.IntegrityError) (1062, \"Duplicate entry '4e670640-74fe-4f84-8faf-29280505a119@forum.playvesteria.com' for key 'messages.global_message_id'\")\n",
      "[SQL: INSERT INTO messages (global_message_id, folder_id, from_address_id, provider_email_id, creation_time, submit_time, delivery_time, sender_name, in_reply_to, subject, body, first_in_thread, previous_message_id, domain, language, spam_score, from_internal_domain, subject_prefix) VALUES (%(global_message_id)s, %(folder_id)s, %(from_address_id)s, %(provider_email_id)s, %(creation_time)s, %(submit_time)s, %(delivery_time)s, %(sender_name)s, %(in_reply_to)s, %(subject)s, %(body)s, %(first_in_thread)s, %(previous_message_id)s, %(domain)s, %(language)s, %(spam_score)s, %(from_internal_domain)s, %(subject_prefix)s)]\n",
      "[parameters: {'global_message_id': '4e670640-74fe-4f84-8faf-29280505a119@forum.playvesteria.com', 'folder_id': 12, 'from_address_id': 808, 'provider_email_id': 2153220, 'creation_time': datetime.datetime(2024, 7, 2, 8, 28, 35, 281315, tzinfo=datetime.timezone.utc), 'submit_time': datetime.datetime(2018, 10, 8, 14, 33, 9, tzinfo=datetime.timezone.utc), 'delivery_time': datetime.datetime(2018, 10, 8, 14, 33, 11, tzinfo=datetime.timezone.utc), 'sender_name': 'noreply=playvesteria.com@smtp.playvesteria.com', 'in_reply_to': None, 'subject': '[Vesteria Forums] Confirm your new account', 'body': None, 'first_in_thread': 1, 'previous_message_id': None, 'domain': 'playvesteria.com', 'language': None, 'spam_score': None, 'from_internal_domain': 0, 'subject_prefix': None}]\n",
      "(Background on this error at: https://sqlalche.me/e/20/gkpj)\n",
      "INFO:root:Loaded 250 messages in batch 8\n",
      "ERROR:root:Message 2165988 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Message 2165988 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Error while loading data into database: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n",
      "(pymysql.err.IntegrityError) (1062, \"Duplicate entry 'IooW-6CbR7u0PjHGiosBoQ@ismtpd0044p1mdw1.sendgrid.net' for key 'messages.global_message_id'\")\n",
      "[SQL: INSERT INTO messages (global_message_id, folder_id, from_address_id, provider_email_id, creation_time, submit_time, delivery_time, sender_name, in_reply_to, subject, body, first_in_thread, previous_message_id, domain, language, spam_score, from_internal_domain, subject_prefix) VALUES (%(global_message_id)s, %(folder_id)s, %(from_address_id)s, %(provider_email_id)s, %(creation_time)s, %(submit_time)s, %(delivery_time)s, %(sender_name)s, %(in_reply_to)s, %(subject)s, %(body)s, %(first_in_thread)s, %(previous_message_id)s, %(domain)s, %(language)s, %(spam_score)s, %(from_internal_domain)s, %(subject_prefix)s)]\n",
      "[parameters: {'global_message_id': 'IooW-6CbR7u0PjHGiosBoQ@ismtpd0044p1mdw1.sendgrid.net', 'folder_id': 12, 'from_address_id': 593, 'provider_email_id': 2161220, 'creation_time': datetime.datetime(2024, 7, 2, 8, 28, 39, 440091, tzinfo=datetime.timezone.utc), 'submit_time': datetime.datetime(2018, 11, 11, 11, 20, 51, tzinfo=datetime.timezone.utc), 'delivery_time': datetime.datetime(2018, 11, 11, 11, 20, 53, tzinfo=datetime.timezone.utc), 'sender_name': 'SoundCloud', 'in_reply_to': None, 'subject': 'Maximize your collaboration with private track and playlist sharing on mobile', 'body': None, 'first_in_thread': 1, 'previous_message_id': None, 'domain': 'announcements.soundcloud.com', 'language': None, 'spam_score': None, 'from_internal_domain': 0, 'subject_prefix': None}]\n",
      "(Background on this error at: https://sqlalche.me/e/20/gkpj)\n",
      "INFO:root:Loaded 250 messages in batch 9\n",
      "ERROR:root:Message 2170532 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Message 2170532 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Message 2171556 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Message 2171556 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Error while loading data into database: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n",
      "(pymysql.err.IntegrityError) (1062, \"Duplicate entry 'CAECg8yQM0cROJwWEj80t+bzhhp+oS66_mjQe4X4Y0xv=ArUXsA@mail.gmail.c' for key 'messages.global_message_id'\")\n",
      "[SQL: INSERT INTO messages (global_message_id, folder_id, from_address_id, provider_email_id, creation_time, submit_time, delivery_time, sender_name, in_reply_to, subject, body, first_in_thread, previous_message_id, domain, language, spam_score, from_internal_domain, subject_prefix) VALUES (%(global_message_id)s, %(folder_id)s, %(from_address_id)s, %(provider_email_id)s, %(creation_time)s, %(submit_time)s, %(delivery_time)s, %(sender_name)s, %(in_reply_to)s, %(subject)s, %(body)s, %(first_in_thread)s, %(previous_message_id)s, %(domain)s, %(language)s, %(spam_score)s, %(from_internal_domain)s, %(subject_prefix)s)]\n",
      "[parameters: {'global_message_id': 'CAECg8yQM0cROJwWEj80t+bzhhp+oS66_mjQe4X4Y0xv=ArUXsA@mail.gmail.com', 'folder_id': 12, 'from_address_id': 513, 'provider_email_id': 2169220, 'creation_time': datetime.datetime(2024, 7, 2, 8, 28, 49, 25008, tzinfo=datetime.timezone.utc), 'submit_time': datetime.datetime(2019, 1, 1, 18, 56, 19, tzinfo=datetime.timezone.utc), 'delivery_time': datetime.datetime(2019, 1, 1, 18, 56, 58, tzinfo=datetime.timezone.utc), 'sender_name': 'Reem', 'in_reply_to': None, 'subject': 'MUN Tomorrow', 'body': None, 'first_in_thread': 1, 'previous_message_id': None, 'domain': 'gmail.com', 'language': None, 'spam_score': None, 'from_internal_domain': 0, 'subject_prefix': None}]\n",
      "(Background on this error at: https://sqlalche.me/e/20/gkpj)\n",
      "INFO:root:Loaded 250 messages in batch 10\n",
      "ERROR:root:Message 2181636 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Message 2181636 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Error while loading data into database: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n",
      "(pymysql.err.IntegrityError) (1062, \"Duplicate entry '01000168defbcb06-8554e3c4-bf64-4b46-9f4a-249403ba6eb0-000000@ema' for key 'messages.global_message_id'\")\n",
      "[SQL: INSERT INTO messages (global_message_id, folder_id, from_address_id, provider_email_id, creation_time, submit_time, delivery_time, sender_name, in_reply_to, subject, body, first_in_thread, previous_message_id, domain, language, spam_score, from_internal_domain, subject_prefix) VALUES (%(global_message_id)s, %(folder_id)s, %(from_address_id)s, %(provider_email_id)s, %(creation_time)s, %(submit_time)s, %(delivery_time)s, %(sender_name)s, %(in_reply_to)s, %(subject)s, %(body)s, %(first_in_thread)s, %(previous_message_id)s, %(domain)s, %(language)s, %(spam_score)s, %(from_internal_domain)s, %(subject_prefix)s)]\n",
      "[parameters: {'global_message_id': '01000168defbcb06-8554e3c4-bf64-4b46-9f4a-249403ba6eb0-000000@email.amazonses.com', 'folder_id': 12, 'from_address_id': 882, 'provider_email_id': 2177252, 'creation_time': datetime.datetime(2024, 7, 2, 8, 29, 0, 184243, tzinfo=datetime.timezone.utc), 'submit_time': datetime.datetime(2019, 2, 11, 23, 54, 30, tzinfo=datetime.timezone.utc), 'delivery_time': datetime.datetime(2019, 2, 11, 23, 54, 30, tzinfo=datetime.timezone.utc), 'sender_name': 'Slack', 'in_reply_to': None, 'subject': '[Slack] Notifications from the Vesteria Team workspace for February 12th, 2019 at 2:54 AM', 'body': None, 'first_in_thread': 1, 'previous_message_id': None, 'domain': 'slack.com', 'language': None, 'spam_score': None, 'from_internal_domain': 0, 'subject_prefix': None}]\n",
      "(Background on this error at: https://sqlalche.me/e/20/gkpj)\n",
      "INFO:root:Loaded 250 messages in batch 11\n",
      "ERROR:root:Error while loading data into database: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n",
      "(pymysql.err.IntegrityError) (1062, \"Duplicate entry 'Gi9oyxMbPODP-Wdbk8W5kg.0@notifications.google.com' for key 'messages.global_message_id'\")\n",
      "[SQL: INSERT INTO messages (global_message_id, folder_id, from_address_id, provider_email_id, creation_time, submit_time, delivery_time, sender_name, in_reply_to, subject, body, first_in_thread, previous_message_id, domain, language, spam_score, from_internal_domain, subject_prefix) VALUES (%(global_message_id)s, %(folder_id)s, %(from_address_id)s, %(provider_email_id)s, %(creation_time)s, %(submit_time)s, %(delivery_time)s, %(sender_name)s, %(in_reply_to)s, %(subject)s, %(body)s, %(first_in_thread)s, %(previous_message_id)s, %(domain)s, %(language)s, %(spam_score)s, %(from_internal_domain)s, %(subject_prefix)s)]\n",
      "[parameters: {'global_message_id': 'Gi9oyxMbPODP-Wdbk8W5kg.0@notifications.google.com', 'folder_id': 12, 'from_address_id': 67, 'provider_email_id': 2185252, 'creation_time': datetime.datetime(2024, 7, 2, 8, 29, 18, 762415, tzinfo=datetime.timezone.utc), 'submit_time': datetime.datetime(2019, 4, 21, 14, 49, 9, tzinfo=datetime.timezone.utc), 'delivery_time': datetime.datetime(2019, 4, 21, 14, 49, 11, tzinfo=datetime.timezone.utc), 'sender_name': 'Google', 'in_reply_to': None, 'subject': 'Security alert', 'body': None, 'first_in_thread': 1, 'previous_message_id': None, 'domain': 'accounts.google.com', 'language': None, 'spam_score': None, 'from_internal_domain': 0, 'subject_prefix': None}]\n",
      "(Background on this error at: https://sqlalche.me/e/20/gkpj)\n",
      "INFO:root:Loaded 250 messages in batch 12\n",
      "ERROR:root:Message 2196548 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Message 2196548 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Error while loading data into database: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n",
      "(pymysql.err.IntegrityError) (1062, \"Duplicate entry 'e7586299529bf5707a4883124a1d79b8@osmc.tv' for key 'messages.global_message_id'\")\n",
      "[SQL: INSERT INTO messages (global_message_id, folder_id, from_address_id, provider_email_id, creation_time, submit_time, delivery_time, sender_name, in_reply_to, subject, body, first_in_thread, previous_message_id, domain, language, spam_score, from_internal_domain, subject_prefix) VALUES (%(global_message_id)s, %(folder_id)s, %(from_address_id)s, %(provider_email_id)s, %(creation_time)s, %(submit_time)s, %(delivery_time)s, %(sender_name)s, %(in_reply_to)s, %(subject)s, %(body)s, %(first_in_thread)s, %(previous_message_id)s, %(domain)s, %(language)s, %(spam_score)s, %(from_internal_domain)s, %(subject_prefix)s)]\n",
      "[parameters: {'global_message_id': 'e7586299529bf5707a4883124a1d79b8@osmc.tv', 'folder_id': 12, 'from_address_id': 71, 'provider_email_id': 2193252, 'creation_time': datetime.datetime(2024, 7, 2, 8, 29, 36, 475913, tzinfo=datetime.timezone.utc), 'submit_time': datetime.datetime(2019, 6, 23, 2, 20, 13, tzinfo=datetime.timezone.utc), 'delivery_time': datetime.datetime(2019, 6, 23, 2, 18, 23, tzinfo=datetime.timezone.utc), 'sender_name': 'OSMC', 'in_reply_to': None, 'subject': \"OSMC's June update is here\", 'body': None, 'first_in_thread': 1, 'previous_message_id': None, 'domain': 'osmc.tv', 'language': None, 'spam_score': None, 'from_internal_domain': 0, 'subject_prefix': None}]\n",
      "(Background on this error at: https://sqlalche.me/e/20/gkpj)\n",
      "INFO:root:Loaded 250 messages in batch 13\n",
      "ERROR:root:Message 2205220 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Message 2205220 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Message 2205956 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Message 2205956 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Error while loading data into database: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n",
      "(pymysql.err.IntegrityError) (1062, \"Duplicate entry '9c6db47c-4903-43d0-be95-80f3de578d85@devforum.roblox.com' for key 'messages.global_message_id'\")\n",
      "[SQL: INSERT INTO messages (global_message_id, folder_id, from_address_id, provider_email_id, creation_time, submit_time, delivery_time, sender_name, in_reply_to, subject, body, first_in_thread, previous_message_id, domain, language, spam_score, from_internal_domain, subject_prefix) VALUES (%(global_message_id)s, %(folder_id)s, %(from_address_id)s, %(provider_email_id)s, %(creation_time)s, %(submit_time)s, %(delivery_time)s, %(sender_name)s, %(in_reply_to)s, %(subject)s, %(body)s, %(first_in_thread)s, %(previous_message_id)s, %(domain)s, %(language)s, %(spam_score)s, %(from_internal_domain)s, %(subject_prefix)s)]\n",
      "[parameters: {'global_message_id': '9c6db47c-4903-43d0-be95-80f3de578d85@devforum.roblox.com', 'folder_id': 12, 'from_address_id': 775, 'provider_email_id': 2201252, 'creation_time': datetime.datetime(2024, 7, 2, 8, 29, 44, 79250, tzinfo=datetime.timezone.utc), 'submit_time': datetime.datetime(2019, 8, 13, 16, 36, 39, tzinfo=datetime.timezone.utc), 'delivery_time': datetime.datetime(2019, 8, 13, 16, 36, 40, tzinfo=datetime.timezone.utc), 'sender_name': 'Roblox Developer Forum summary', 'in_reply_to': None, 'subject': '[Roblox Developer Forum] Summary', 'body': None, 'first_in_thread': 1, 'previous_message_id': None, 'domain': 'devforum.roblox.com', 'language': None, 'spam_score': None, 'from_internal_domain': 0, 'subject_prefix': None}]\n",
      "(Background on this error at: https://sqlalche.me/e/20/gkpj)\n",
      "INFO:root:Loaded 250 messages in batch 14\n",
      "ERROR:root:Message 2210116 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Message 2210116 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Error while loading data into database: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n",
      "(pymysql.err.IntegrityError) (1062, \"Duplicate entry '7684085f-a85b-4553-bae2-a94edb3dcf59@devforum.roblox.com' for key 'messages.global_message_id'\")\n",
      "[SQL: INSERT INTO messages (global_message_id, folder_id, from_address_id, provider_email_id, creation_time, submit_time, delivery_time, sender_name, in_reply_to, subject, body, first_in_thread, previous_message_id, domain, language, spam_score, from_internal_domain, subject_prefix) VALUES (%(global_message_id)s, %(folder_id)s, %(from_address_id)s, %(provider_email_id)s, %(creation_time)s, %(submit_time)s, %(delivery_time)s, %(sender_name)s, %(in_reply_to)s, %(subject)s, %(body)s, %(first_in_thread)s, %(previous_message_id)s, %(domain)s, %(language)s, %(spam_score)s, %(from_internal_domain)s, %(subject_prefix)s)]\n",
      "[parameters: {'global_message_id': '7684085f-a85b-4553-bae2-a94edb3dcf59@devforum.roblox.com', 'folder_id': 12, 'from_address_id': 775, 'provider_email_id': 2209252, 'creation_time': datetime.datetime(2024, 7, 2, 8, 29, 52, 678114, tzinfo=datetime.timezone.utc), 'submit_time': datetime.datetime(2019, 10, 8, 14, 12, 42, tzinfo=datetime.timezone.utc), 'delivery_time': datetime.datetime(2019, 10, 8, 14, 12, 45, tzinfo=datetime.timezone.utc), 'sender_name': 'Roblox Developer Forum summary', 'in_reply_to': None, 'subject': '[Roblox Developer Forum] Summary', 'body': None, 'first_in_thread': 1, 'previous_message_id': None, 'domain': 'devforum.roblox.com', 'language': None, 'spam_score': None, 'from_internal_domain': 0, 'subject_prefix': None}]\n",
      "(Background on this error at: https://sqlalche.me/e/20/gkpj)\n",
      "INFO:root:Loaded 250 messages in batch 15\n",
      "ERROR:root:Message 2219524 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Message 2219524 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Error while loading data into database: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n",
      "(pymysql.err.IntegrityError) (1062, \"Duplicate entry '4c19a5a7-d3e4-46dd-81a2-0bbf5d951146@devforum.roblox.com' for key 'messages.global_message_id'\")\n",
      "[SQL: INSERT INTO messages (global_message_id, folder_id, from_address_id, provider_email_id, creation_time, submit_time, delivery_time, sender_name, in_reply_to, subject, body, first_in_thread, previous_message_id, domain, language, spam_score, from_internal_domain, subject_prefix) VALUES (%(global_message_id)s, %(folder_id)s, %(from_address_id)s, %(provider_email_id)s, %(creation_time)s, %(submit_time)s, %(delivery_time)s, %(sender_name)s, %(in_reply_to)s, %(subject)s, %(body)s, %(first_in_thread)s, %(previous_message_id)s, %(domain)s, %(language)s, %(spam_score)s, %(from_internal_domain)s, %(subject_prefix)s)]\n",
      "[parameters: {'global_message_id': '4c19a5a7-d3e4-46dd-81a2-0bbf5d951146@devforum.roblox.com', 'folder_id': 12, 'from_address_id': 775, 'provider_email_id': 2217252, 'creation_time': datetime.datetime(2024, 7, 2, 8, 30, 3, 766353, tzinfo=datetime.timezone.utc), 'submit_time': datetime.datetime(2019, 11, 24, 14, 0, 6, tzinfo=datetime.timezone.utc), 'delivery_time': datetime.datetime(2019, 11, 24, 14, 0, 12, tzinfo=datetime.timezone.utc), 'sender_name': 'Roblox Developer Forum summary', 'in_reply_to': None, 'subject': '[Roblox Developer Forum] Summary', 'body': None, 'first_in_thread': 1, 'previous_message_id': None, 'domain': 'devforum.roblox.com', 'language': None, 'spam_score': None, 'from_internal_domain': 0, 'subject_prefix': None}]\n",
      "(Background on this error at: https://sqlalche.me/e/20/gkpj)\n",
      "INFO:root:Loaded 250 messages in batch 16\n",
      "ERROR:root:Message 2227396 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Message 2227396 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Message 2229444 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Message 2229444 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Error getting value for key conversation_topic: pypff_message_get_conversation_topic: unable to retrieve conversation topic size. libuna_unicode_character_copy_from_utf16_stream: unsupported UTF-16 character. libuna_utf8_string_size_from_utf16_stream: unable to copy Unicode character from UTF-16 stream. libpff_mapi_value_get_data_as_utf8_string_size: unable to determine size of value data as UTF-8 string. libpff_record_entry_get_data_as_utf8_string_size_with_codepage: unable to determine size of value data as UTF-8 string. libpff_internal_item_get_entry_value_utf8_string_size: unable to retrieve UTF-8 string size. libpff_message_get_entry_value_utf8_string_size: unable to retrieve UTF-8 string size.\n",
      "ERROR:root:Error while loading data into database: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n",
      "(pymysql.err.IntegrityError) (1062, \"Duplicate entry '82h97TTgS4uqzhxgo0FS4A@ismtpd0022p1iad2.sendgrid.net' for key 'messages.global_message_id'\")\n",
      "[SQL: INSERT INTO messages (global_message_id, folder_id, from_address_id, provider_email_id, creation_time, submit_time, delivery_time, sender_name, in_reply_to, subject, body, first_in_thread, previous_message_id, domain, language, spam_score, from_internal_domain, subject_prefix) VALUES (%(global_message_id)s, %(folder_id)s, %(from_address_id)s, %(provider_email_id)s, %(creation_time)s, %(submit_time)s, %(delivery_time)s, %(sender_name)s, %(in_reply_to)s, %(subject)s, %(body)s, %(first_in_thread)s, %(previous_message_id)s, %(domain)s, %(language)s, %(spam_score)s, %(from_internal_domain)s, %(subject_prefix)s)]\n",
      "[parameters: {'global_message_id': '82h97TTgS4uqzhxgo0FS4A@ismtpd0022p1iad2.sendgrid.net', 'folder_id': 12, 'from_address_id': 929, 'provider_email_id': 2225252, 'creation_time': datetime.datetime(2024, 7, 2, 8, 30, 10, 509400, tzinfo=datetime.timezone.utc), 'submit_time': datetime.datetime(2020, 1, 31, 20, 56, 22, tzinfo=datetime.timezone.utc), 'delivery_time': datetime.datetime(2020, 1, 31, 20, 56, 23, tzinfo=datetime.timezone.utc), 'sender_name': 'Spotify', 'in_reply_to': None, 'subject': 'New music from artists you love, with Midnight Kids on your Release Radar now', 'body': None, 'first_in_thread': 1, 'previous_message_id': None, 'domain': 'spotify.com', 'language': None, 'spam_score': None, 'from_internal_domain': 0, 'subject_prefix': None}]\n",
      "(Background on this error at: https://sqlalche.me/e/20/gkpj)\n",
      "INFO:root:Loaded 250 messages in batch 17\n",
      "ERROR:root:Error while loading data into database: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n",
      "(pymysql.err.IntegrityError) (1062, \"Duplicate entry '010001716a861774-25957681-2a4f-4983-bf72-53f26a7d3a86-000000@ema' for key 'messages.global_message_id'\")\n",
      "[SQL: INSERT INTO messages (global_message_id, folder_id, from_address_id, provider_email_id, creation_time, submit_time, delivery_time, sender_name, in_reply_to, subject, body, first_in_thread, previous_message_id, domain, language, spam_score, from_internal_domain, subject_prefix) VALUES (%(global_message_id)s, %(folder_id)s, %(from_address_id)s, %(provider_email_id)s, %(creation_time)s, %(submit_time)s, %(delivery_time)s, %(sender_name)s, %(in_reply_to)s, %(subject)s, %(body)s, %(first_in_thread)s, %(previous_message_id)s, %(domain)s, %(language)s, %(spam_score)s, %(from_internal_domain)s, %(subject_prefix)s)]\n",
      "[parameters: {'global_message_id': '010001716a861774-25957681-2a4f-4983-bf72-53f26a7d3a86-000000@email.amazonses.com', 'folder_id': 12, 'from_address_id': 1087, 'provider_email_id': 2233252, 'creation_time': datetime.datetime(2024, 7, 2, 8, 30, 19, 828367, tzinfo=datetime.timezone.utc), 'submit_time': datetime.datetime(2020, 4, 11, 18, 35, 4, tzinfo=datetime.timezone.utc), 'delivery_time': datetime.datetime(2020, 4, 11, 18, 35, 6, tzinfo=datetime.timezone.utc), 'sender_name': 'Reddit', 'in_reply_to': None, 'subject': '\"Simple and clean\"', 'body': None, 'first_in_thread': 1, 'previous_message_id': None, 'domain': 'redditmail.com', 'language': None, 'spam_score': None, 'from_internal_domain': 0, 'subject_prefix': None}]\n",
      "(Background on this error at: https://sqlalche.me/e/20/gkpj)\n",
      "INFO:root:Loaded 250 messages in batch 18\n",
      "ERROR:root:Message 2242916 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Message 2242916 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Message 2243108 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Message 2243108 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Message 2244132 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Message 2244132 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Message 2246340 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Message 2246340 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Error while loading data into database: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n",
      "(pymysql.err.IntegrityError) (1062, \"Duplicate entry '1592593373562.d02cae89-2fea-4727-a555-f602b5edd27d@bf05x.hubspot' for key 'messages.global_message_id'\")\n",
      "[SQL: INSERT INTO messages (global_message_id, folder_id, from_address_id, provider_email_id, creation_time, submit_time, delivery_time, sender_name, in_reply_to, subject, body, first_in_thread, previous_message_id, domain, language, spam_score, from_internal_domain, subject_prefix) VALUES (%(global_message_id)s, %(folder_id)s, %(from_address_id)s, %(provider_email_id)s, %(creation_time)s, %(submit_time)s, %(delivery_time)s, %(sender_name)s, %(in_reply_to)s, %(subject)s, %(body)s, %(first_in_thread)s, %(previous_message_id)s, %(domain)s, %(language)s, %(spam_score)s, %(from_internal_domain)s, %(subject_prefix)s)]\n",
      "[parameters: {'global_message_id': '1592593373562.d02cae89-2fea-4727-a555-f602b5edd27d@bf05x.hubspotemail.net', 'folder_id': 12, 'from_address_id': 1111, 'provider_email_id': 2241252, 'creation_time': datetime.datetime(2024, 7, 2, 8, 30, 30, 980162, tzinfo=datetime.timezone.utc), 'submit_time': datetime.datetime(2020, 6, 19, 19, 12, 51, tzinfo=datetime.timezone.utc), 'delivery_time': datetime.datetime(2020, 6, 19, 19, 12, 53, tzinfo=datetime.timezone.utc), 'sender_name': 'Droplr Team', 'in_reply_to': None, 'subject': 'Droplr Digest: Get more out of your account', 'body': None, 'first_in_thread': 1, 'previous_message_id': None, 'domain': 'droplr.com', 'language': None, 'spam_score': None, 'from_internal_domain': 0, 'subject_prefix': None}]\n",
      "(Background on this error at: https://sqlalche.me/e/20/gkpj)\n",
      "INFO:root:Loaded 250 messages in batch 19\n",
      "ERROR:root:Message 2250468 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Message 2250468 has no recipients\n",
      "ERROR:root:Failed to validate message: Message has no recipients\n",
      "ERROR:root:Error while loading data into database: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n",
      "(pymysql.err.IntegrityError) (1062, \"Duplicate entry '1597356321305.e95e78a8-2e8f-4884-af67-6547b197d7b3@bf06x.hubspot' for key 'messages.global_message_id'\")\n",
      "[SQL: INSERT INTO messages (global_message_id, folder_id, from_address_id, provider_email_id, creation_time, submit_time, delivery_time, sender_name, in_reply_to, subject, body, first_in_thread, previous_message_id, domain, language, spam_score, from_internal_domain, subject_prefix) VALUES (%(global_message_id)s, %(folder_id)s, %(from_address_id)s, %(provider_email_id)s, %(creation_time)s, %(submit_time)s, %(delivery_time)s, %(sender_name)s, %(in_reply_to)s, %(subject)s, %(body)s, %(first_in_thread)s, %(previous_message_id)s, %(domain)s, %(language)s, %(spam_score)s, %(from_internal_domain)s, %(subject_prefix)s)]\n",
      "[parameters: {'global_message_id': '1597356321305.e95e78a8-2e8f-4884-af67-6547b197d7b3@bf06x.hubspotemail.net', 'folder_id': 12, 'from_address_id': 606, 'provider_email_id': 2249252, 'creation_time': datetime.datetime(2024, 7, 2, 8, 30, 41, 362983, tzinfo=datetime.timezone.utc), 'submit_time': datetime.datetime(2020, 8, 13, 22, 12, 45, tzinfo=datetime.timezone.utc), 'delivery_time': datetime.datetime(2020, 8, 13, 22, 12, 45, tzinfo=datetime.timezone.utc), 'sender_name': 'Peter Dufresne', 'in_reply_to': None, 'subject': 'New! See the Agenda for the Model G20 Virtual Summit', 'body': None, 'first_in_thread': 1, 'previous_message_id': None, 'domain': 'knovva.com', 'language': None, 'spam_score': None, 'from_internal_domain': 0, 'subject_prefix': None}]\n",
      "(Background on this error at: https://sqlalche.me/e/20/gkpj)\n",
      "INFO:root:Loaded 250 messages in batch 20\n",
      "ERROR:root:Error while loading data into database: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)\n",
      "(pymysql.err.IntegrityError) (1062, \"Duplicate entry '6b64e7a8448844208a8e29f362a12b07@795651218' for key 'messages.global_message_id'\")\n",
      "[SQL: INSERT INTO messages (global_message_id, folder_id, from_address_id, provider_email_id, creation_time, submit_time, delivery_time, sender_name, in_reply_to, subject, body, first_in_thread, previous_message_id, domain, language, spam_score, from_internal_domain, subject_prefix) VALUES (%(global_message_id)s, %(folder_id)s, %(from_address_id)s, %(provider_email_id)s, %(creation_time)s, %(submit_time)s, %(delivery_time)s, %(sender_name)s, %(in_reply_to)s, %(subject)s, %(body)s, %(first_in_thread)s, %(previous_message_id)s, %(domain)s, %(language)s, %(spam_score)s, %(from_internal_domain)s, %(subject_prefix)s)]\n",
      "[parameters: {'global_message_id': '6b64e7a8448844208a8e29f362a12b07@795651218', 'folder_id': 12, 'from_address_id': 70, 'provider_email_id': 2257252, 'creation_time': datetime.datetime(2024, 7, 2, 8, 30, 46, 674030, tzinfo=datetime.timezone.utc), 'submit_time': datetime.datetime(2020, 10, 27, 16, 1, 37, tzinfo=datetime.timezone.utc), 'delivery_time': datetime.datetime(2020, 10, 27, 16, 12, 20, tzinfo=datetime.timezone.utc), 'sender_name': 'Unity', 'in_reply_to': None, 'subject': 'The LEGO® Microgame is here!', 'body': None, 'first_in_thread': 1, 'previous_message_id': None, 'domain': 'unity3d.com', 'language': None, 'spam_score': None, 'from_internal_domain': 0, 'subject_prefix': None}]\n",
      "(Background on this error at: https://sqlalche.me/e/20/gkpj)\n",
      "INFO:root:Loaded 39 messages in batch 21\n",
      "INFO:root:Skipping empty folder: Outbox\n",
      "INFO:root:Skipping empty folder: Sync Issues (This computer only)\n",
      "INFO:root:Skipping empty folder: [Gmail]\n",
      "INFO:root:Skipping empty folder: Banking\n",
      "INFO:root:Skipping empty folder: Notes\n",
      "INFO:root:Skipping empty folder: Receipt\n",
      "INFO:root:Exported folders to CSV\n",
      "INFO:root:Exported addresses to CSV\n",
      "INFO:root:Exported messages to CSV\n",
      "INFO:root:Exported recipients to CSV\n",
      "INFO:root:Database connection closed\n"
     ]
    }
   ],
   "source": [
    "loader.create_tables()\n",
    "\n",
    "for message_batch in extractor.extract_messages():\n",
    "    enriched_messages: List[EnrichedMessage] = []\n",
    "    \n",
    "    for pst_message in message_batch.messages:\n",
    "        provider_email_id = pst_message.provider_email_id\n",
    "        # logging.info(f\"Processing message {provider_email_id}\")\n",
    "        try:\n",
    "            parsed_message: ParsedMessage = message_parser.parse(pst_message.message, provider_email_id, pst_message.folder_name)\n",
    "        except Exception as e:\n",
    "            continue\n",
    "\n",
    "        try:\n",
    "            enriched_message: EnrichedMessage = message_enricher.enrich_message(parsed_message)\n",
    "        except Exception as e:\n",
    "            continue\n",
    "        else:\n",
    "            enriched_messages.append(enriched_message)\n",
    "\n",
    "    try:\n",
    "        loader.load(enriched_messages)\n",
    "    except SQLAlchemyError as e:\n",
    "        logging.error(f\"Error loading messages in batch {message_batch.batch_id}: {e}\")\n",
    "        continue\n",
    "    else:\n",
    "        logging.info(f\"Loaded {len(enriched_messages)} messages in batch {message_batch.batch_id}\")\n",
    "\n",
    "loader.export_to_csv(\"./data/processed\")\n",
    "loader.close()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "email_analysis",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
